"use client";
import Nav from '@app/components/Nav';
import Provider from '@app/components/Provider';
import '@styles/globals.css';
import { ThemeProvider } from "next-themes"


const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class">
          <Provider>
            <div className="main">
              <div className="gradient">
              </div>
            </div>
            <main className="app bg-white dark:bg-slate-800 ">
              <Nav />
              {children}
            </main>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  )
}

